### ISSUE TITLE
null-sized destination on ftp server side

### ISSUE THREAD

**Issue by yargeel** [linkindrew/easyFTP#2]
hello!

i'm trying to upload file on an ftp-server. 
both of my own code and your example create null-sized destination file without any error in logs. 

how to catch the cause of the problem?

**Comment by Ryan1729** [comment]
I was having this same problem, then I saw a comment on this [stackoverflow answer](http://stackoverflow.com/a/1651337/4496839) that suggested calling `enterLocalPassiveMode();` between login and connect.

So I put `mFtpClient.enterLocalPassiveMode();` right after [this line](https://github.com/linkindrew/easyFTP/blob/master/library/src/main/java/com/adeel/library/easyFTP.java#L95) in the library and tried again and it successfully uploaded the file!

[Here's](https://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPClient.html#enterLocalPassiveMode()) the docs for that method in the underlying apache lib.
