### ISSUE TITLE
How can I get Upload and Download Transfer rate?

### ISSUE THREAD

**Issue by Reegan01** [linkindrew/easyFTP#5]
Hi Friend,

Thanks for your easiest FTP plugin. 

I just used followed these steps for manually calculate the Transfer rate(Throughput):

inside ```protected String doInBackground(String... params) { ```
```
File imgFile = new File(params[4]); // params[4] - full file path
imgSizeBytes = imgFile.length();
InputStream is= new FileInputStream(params[4]);
upload_start = System.currentTimeMillis();
ftp.uploadFile(is,params[3]);
upload_end = System.currentTimeMillis();
```
inside ```protected void onPostExecute(String str) {```
```
float timeDifference = upload_end - upload_start;
uploadThroughput = ((imgSizeBytes * 8) / 1000000) / (timeDifference / 1000);
```

Same thing I did with download Transfer rate.

Finally I got 
```
Upload Throughput :  0.48 Mbps
Download Throughput : 5.01 Mbps
```

Please tell me, Am I correct on that formula? or You already have any predefined method to calculate the Transfer rate. It is too slow on upload a file with LTE 4G network.  But download is okay.

**Comment by adeelahmad94** [comment]
I am not a network expert so kindly verify your calculations on stackoverflow. Having said that, do try out different networks and note the pattern. I believe it has nothing to do with implementation of library.
